name: TechCrunch Crawler

on:
  # 每小时运行一次
  schedule:
    - cron: '0 * * * *'
  
  # 允许手动触发
  workflow_dispatch:
    inputs:
      hours:
        description: '时间限制（小时）'
        required: false
        default: '24'
        type: string

env:
  PYTHON_VERSION: '3.11'

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create config from secrets
      run: |
        cat > config.json << EOF
        {
          "supabase": {
            "enabled": true,
            "url": "${{ secrets.SUPABASE_URL }}",
            "anon_key": "${{ secrets.SUPABASE_ANON_KEY }}",
            "table_name": "news_items"
          }
        }
        EOF
    
    - name: Run crawler
      run: |
        python automated_crawler.py
      env:
        HOURS: ${{ github.event.inputs.hours || '24' }}
    
    - name: Upload logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: crawler-logs
        path: |
          *.log
          *.json
        retention-days: 7